### ISSUE TITLE
Can't run two Kotti apps in the same Python process

### ISSUE THREAD

**Issue by chrneumann** [Kotti/Kotti#113] opened 2012-08-09 08:58 UTC
Kotti is apparently not thread safe. For example, if two kotti instances run in the same Python process, things get really messed up:

```ini
[app:kotti2]
use = egg:kotti
---snip---

[app:kotti]
use = egg:kotti
---different DB, configuration, ...---
---snip---

[filter:fanstatic]
use = egg:fanstatic#fanstatic

[server:main]
use = egg:waitress#main
host = localhost
port = 5000

[composite:main]
use = egg:Paste#urlmap
/one = kotti2
/two = kotti
```

The problem seems to be the use of globals in Kotti, e,g, kotti.views.events uses globals to register event listeners. A solution could be to use thread-local data structures. Or don't use the globals at all but pass them around, maybe using pyramid's registry in some way?

IMHO kotti should be thread safe. It is some extra work, but worth it.

**Comment by davidemoro** [comment] 2015-06-24 10:14
Confirmed: I tried to configure a composite app with two kotti applications and it seems that they use the same database connection url with double rendered slots (kotti_navigation).

**Comment by dnouri** [comment] 2015-06-24 11:18
Yeah this isn't gonna work for a number of reasons.

**Comment by davidemoro** [comment] 2015-06-25 06:00
@dnouri is there a document online with a map of all kotti pieces of code that need to be converted for thread safety?

**Comment by dnouri** [comment] 2015-06-27 14:36
@davidemoro I don't have one.

**Comment by chrneumann** [comment] 2015-06-27 18:28
You also have to make sure that the Python packages Kotti uses are thread safe as well. IIRC, that's often not the case (generally speakting for Python packages).

**Comment by tiberiuichim** [comment] 2015-06-27 19:58
But what is the real use case? Where would it be absolutely needed to run 2 Kottis in the same process, and why can't that be solved in some other simpler way?

depot (the new dependency added to support blobs on disk) is not thread safe, but could probably be made, with a little bit of effort.

**Comment by chrneumann** [comment] 2015-06-28 05:43
My use case was to have multiple websites running on the same memory limited server. Each site having its own Kotti process consumes more memory than one process for all sites.

**Comment by davidemoro** [comment] 2015-07-09 11:04
I see the @chrneumann's point, same need for me (multiple websites in a single process).
For now I've but you can find alternative solutions too, I was just curious about the status of this ticket

**Comment by disko** [comment] 2016-10-11 07:37
Closing as it's not supported and nobody seems to be interested in that use case anymore.

**Closed by disko** 2016-10-11 07:37 UTC
Labels: Python
