### ISSUE TITLE
getPreventDefault() is deprecated

### ISSUE THREAD

**Issue by Dog** [Kotti/Kotti#367] opened 2015-01-06 08:29 UTC
I get a warning in console from jQuery that getPreventDefault() is deprecated. It suggests using defaultPrevented instead.

I see this warning on every page with a fresh installation.

**Comment by disko** [comment] 2015-01-07 14:44
I cannot reproduce this at all.  Did you install the requirements with ``pip install -r requirements.txt``?

**Comment by disko** [comment] 2015-01-07 16:32
Closing for now.  Please reopen with description how to reproduce if you can.

**Closed by disko** 2015-01-07 16:32 UTC
Labels: Frontend
